name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build and Push
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: print-stuff
        run: |
          env
          pwd
          ls -lahrt
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jaredmcqueen/jira-scraper:latest
      - name: Checkout k8s repo
        uses: actions/checkout@v2
        with:
          repository: jaredmcqueen/k8s-deployments
          path: k8s-deployments
      - name: modify app version
        run: |
          env
          pwd
          ls -lahrt
          ls *
          sed -E -i'' "s/(.*jira-scraper:).*/\1${GITHUB_SHA:0:7}/" 'jira-scraper/jira-scraper-deployment.yaml'
          cat jira-scraper-deployment.yaml
